services:

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: "SuaSenhaF0rte!23"
      MYSQL_DATABASE: BD23121
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - usuario-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pSuaSenhaF0rte!23"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 45s

  usuario-api:
    build: .
    container_name: usuario-api-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/BD23121?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: "SuaSenhaF0rte!23"
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - usuario-network
    restart: unless-stopped

volumes:
  mysql-data:

networks:
  usuario-network:
    driver: bridge